spring:
  application:
    name: clinica

  datasource:
    url: jdbc:mysql://localhost:3306/mysql-clinica?useSSL=false&serverTimezone=UTC
    username: root
    password: senha123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

gateway:
  busca-cep:
    url: https://brasilapi.com.br/



